name: chicago-bus-hello
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: your-github-username/chicago_bus_hello
  build_command: pip install -r requirements.txt
  run_command: gunicorn app:app --bind 0.0.0.0:8080
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: FLASK_ENV
    value: production
  - key: CTA_API_KEY
    type: SECRET
    value: ${CTA_API_KEY}
  - key: PYTHONUNBUFFERED
    value: "1"
  health_check:
    http_path: /api/routes
    initial_delay_seconds: 30
    period_seconds: 60
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3 